# Generated by Django 6.0.5 on 2026-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('passport_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('academic_details', models.TextField(blank=True, db_index=True, null=True)),
                ('test_score', models.FloatField(blank=True, null=True)),
                ('preferred_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rac_students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
