# Generated by Django 6.0.5 on 2026-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_racstudent_dedup_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racstudent',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='racstudent',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='racstudent',
            name='passport_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
