# Generated by Django 6.0.5 on 2026-09-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_alter_racstudent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racstudent',
            name='created_by',
            field=models.EmailField(blank=True, help_text='Email of the logged-in user who created/uploaded this record.', max_length=254, null=True),
        ),
    ]
