# Generated by Django 6.0.5 on 2026-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_racstudent_options_studentactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racstudent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('not_sure', 'Not Sure')], db_index=True, default='not_sure', max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentActivity',
        ),
    ]
