# Generated by Django 6.0.5 on 2026-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_racstudent_status_delete_studentactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racstudent',
            name='intake_date',
        ),
        migrations.AddField(
            model_name='racstudent',
            name='intake',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('not_sure', 'Not Sure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='racstudent',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2026, null=True),
        ),
    ]
