# Generated by Django 6.0.5 on 2026-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_remove_racstudent_intake_date_racstudent_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racstudent',
            name='intake',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Not Sure', 'Not Sure')], max_length=20, null=True),
        ),
    ]
