# Generated by Django 6.0.5 on 2026-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_racstudent_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racstudent',
            name='intake',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('not_sure', 'Not Sure')], max_length=20, null=True),
        ),
    ]
