# Generated by Django 6.0.5 on 2026-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_alter_racstudent_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racstudent',
            name='status',
            field=models.CharField(choices=[('not_interested', 'Not Interested'), ('interested', 'Interested'), ('not_sure', 'Not Sure'), ('shortlisting_done', 'Shortlisting Done'), ('docs_shared', 'Docs Shared'), ('applied', 'Applied'), ('deposit_paid', 'Deposit Paid'), ('visa_granted', 'Visa Granted')], db_index=True, default='not_sure', max_length=20),
        ),
    ]
