# Generated by Django 6.0.5 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_normalize_legacy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='racstudent',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='racstudent',
            name='source_file',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
