# Generated by Django 6.0.5 on 2026-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_studentreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racstudent',
            name='intake',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('not_sure', 'Not Sure')], default='not_sure', max_length=20, null=True),
        ),
    ]
