# Generated by Django 6.0.5 on 2026-10-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_alter_racstudent_intake'),
        ('CRM', '0018_intake_blank_to_not_sure'),
    ]

    operations = [
    ]
