# Generated by Django 6.0.5 on 2026-10-07 11:37

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_add_new_student_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('organisation_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.EmailField(blank=True, help_text='Email of the logged-in user who added this record.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rac_colleges',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(db_index=True, max_length=255)),
                ('intake', models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('winter', 'Winter'), ('not_sure', 'Not Sure')], default='not_sure', max_length=20, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=CRM.models.default_year, null=True)),
                ('university', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('due', 'Due'), ('on_date', 'On Date')], default='due', max_length=20, null=True)),
                ('status', models.CharField(choices=[('payment_done', 'Payment Done'), ('payment_pending', 'Payment Pending'), ('half_payment_done', 'Half Payment Done')], db_index=True, default='payment_pending', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('university_payment', 'University Payment'), ('prm', 'PRM'), ('flywire', 'Flywire'), ('el', 'EL'), ('accommodation', 'Accommodation'), ('test_prep', 'Test Prep')], db_index=True, max_length=30, null=True)),
                ('created_by', models.EmailField(blank=True, help_text='Email of the logged-in user who added this record.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rac_payments',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
