# Generated by Django 6.0.5 on 2026-10-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0022_alter_racstudent_intake'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table='rac_universities',
        ),
    ]
