# Generated by Django 6.0.5 on 2026-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_alter_university_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='racstudent',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
